/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AtivarConviteRouteImport } from './routes/ativar-convite'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSolicitarAcessoRouteImport } from './routes/_authenticated/solicitar-acesso'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedMinhaEquipeRouteImport } from './routes/_authenticated/minha-equipe'
import { Route as AuthenticatedContaRouteImport } from './routes/_authenticated/conta'
import { Route as AuthenticatedAreaDeTrabalhoRouteImport } from './routes/_authenticated/area-de-trabalho'
import { Route as AuthenticatedAlterarOrgaoRouteImport } from './routes/_authenticated/alterar-orgao'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AuthenticatedAdminSolicitacoesRouteImport } from './routes/_authenticated/admin/solicitacoes'
import { Route as AuthenticatedAdminOrgaosRouteImport } from './routes/_authenticated/admin/orgaos'
import { Route as AuthenticatedAdminTecnicoVinculosRouteImport } from './routes/_authenticated/admin-tecnico/vinculos'
import { Route as AuthenticatedAdminTecnicoUsuariosRouteImport } from './routes/_authenticated/admin-tecnico/usuarios'
import { Route as AuthenticatedAdminTecnicoSegurancaRouteImport } from './routes/_authenticated/admin-tecnico/seguranca'
import { Route as AuthenticatedAdminTecnicoPainelRouteImport } from './routes/_authenticated/admin-tecnico/painel'
import { Route as AuthenticatedAdminTecnicoOrgaosRouteImport } from './routes/_authenticated/admin-tecnico/orgaos'
import { Route as AuthenticatedAdminTecnicoDiagnosticosRouteImport } from './routes/_authenticated/admin-tecnico/diagnosticos'
import { Route as AuthenticatedAdminTecnicoConfiguracoesRouteImport } from './routes/_authenticated/admin-tecnico/configuracoes'
import { Route as AuthenticatedAdminTecnicoAuditoriaRouteImport } from './routes/_authenticated/admin-tecnico/auditoria'
import { Route as AuthenticatedAdminTecnicoAdministradoresRouteImport } from './routes/_authenticated/admin-tecnico/administradores'
import { Route as AuthenticatedAdminTecnicoAcessoGlobalRouteImport } from './routes/_authenticated/admin-tecnico/acesso-global'
import { Route as AuthenticatedAdminTecnicoAcessoEmergencialRouteImport } from './routes/_authenticated/admin-tecnico/acesso-emergencial'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'

const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AtivarConviteRoute = AtivarConviteRouteImport.update({
  id: '/ativar-convite',
  path: '/ativar-convite',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSolicitarAcessoRoute =
  AuthenticatedSolicitarAcessoRouteImport.update({
    id: '/solicitar-acesso',
    path: '/solicitar-acesso',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMinhaEquipeRoute =
  AuthenticatedMinhaEquipeRouteImport.update({
    id: '/minha-equipe',
    path: '/minha-equipe',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContaRoute = AuthenticatedContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAreaDeTrabalhoRoute =
  AuthenticatedAreaDeTrabalhoRouteImport.update({
    id: '/area-de-trabalho',
    path: '/area-de-trabalho',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAlterarOrgaoRoute =
  AuthenticatedAlterarOrgaoRouteImport.update({
    id: '/alterar-orgao',
    path: '/alterar-orgao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminSolicitacoesRoute =
  AuthenticatedAdminSolicitacoesRouteImport.update({
    id: '/admin/solicitacoes',
    path: '/admin/solicitacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminOrgaosRoute =
  AuthenticatedAdminOrgaosRouteImport.update({
    id: '/admin/orgaos',
    path: '/admin/orgaos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminTecnicoVinculosRoute =
  AuthenticatedAdminTecnicoVinculosRouteImport.update({
    id: '/admin-tecnico/vinculos',
    path: '/admin-tecnico/vinculos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminTecnicoUsuariosRoute =
  AuthenticatedAdminTecnicoUsuariosRouteImport.update({
    id: '/admin-tecnico/usuarios',
    path: '/admin-tecnico/usuarios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminTecnicoSegurancaRoute =
  AuthenticatedAdminTecnicoSegurancaRouteImport.update({
    id: '/admin-tecnico/seguranca',
    path: '/admin-tecnico/seguranca',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminTecnicoPainelRoute =
  AuthenticatedAdminTecnicoPainelRouteImport.update({
    id: '/admin-tecnico/painel',
    path: '/admin-tecnico/painel',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminTecnicoOrgaosRoute =
  AuthenticatedAdminTecnicoOrgaosRouteImport.update({
    id: '/admin-tecnico/orgaos',
    path: '/admin-tecnico/orgaos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminTecnicoDiagnosticosRoute =
  AuthenticatedAdminTecnicoDiagnosticosRouteImport.update({
    id: '/admin-tecnico/diagnosticos',
    path: '/admin-tecnico/diagnosticos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminTecnicoConfiguracoesRoute =
  AuthenticatedAdminTecnicoConfiguracoesRouteImport.update({
    id: '/admin-tecnico/configuracoes',
    path: '/admin-tecnico/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminTecnicoAuditoriaRoute =
  AuthenticatedAdminTecnicoAuditoriaRouteImport.update({
    id: '/admin-tecnico/auditoria',
    path: '/admin-tecnico/auditoria',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminTecnicoAdministradoresRoute =
  AuthenticatedAdminTecnicoAdministradoresRouteImport.update({
    id: '/admin-tecnico/administradores',
    path: '/admin-tecnico/administradores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminTecnicoAcessoGlobalRoute =
  AuthenticatedAdminTecnicoAcessoGlobalRouteImport.update({
    id: '/admin-tecnico/acesso-global',
    path: '/admin-tecnico/acesso-global',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminTecnicoAcessoEmergencialRoute =
  AuthenticatedAdminTecnicoAcessoEmergencialRouteImport.update({
    id: '/admin-tecnico/acesso-emergencial',
    path: '/admin-tecnico/acesso-emergencial',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ativar-convite': typeof AtivarConviteRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/alterar-orgao': typeof AuthenticatedAlterarOrgaoRoute
  '/area-de-trabalho': typeof AuthenticatedAreaDeTrabalhoRoute
  '/conta': typeof AuthenticatedContaRoute
  '/minha-equipe': typeof AuthenticatedMinhaEquipeRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/solicitar-acesso': typeof AuthenticatedSolicitarAcessoRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin-tecnico/acesso-emergencial': typeof AuthenticatedAdminTecnicoAcessoEmergencialRoute
  '/admin-tecnico/acesso-global': typeof AuthenticatedAdminTecnicoAcessoGlobalRoute
  '/admin-tecnico/administradores': typeof AuthenticatedAdminTecnicoAdministradoresRoute
  '/admin-tecnico/auditoria': typeof AuthenticatedAdminTecnicoAuditoriaRoute
  '/admin-tecnico/configuracoes': typeof AuthenticatedAdminTecnicoConfiguracoesRoute
  '/admin-tecnico/diagnosticos': typeof AuthenticatedAdminTecnicoDiagnosticosRoute
  '/admin-tecnico/orgaos': typeof AuthenticatedAdminTecnicoOrgaosRoute
  '/admin-tecnico/painel': typeof AuthenticatedAdminTecnicoPainelRoute
  '/admin-tecnico/seguranca': typeof AuthenticatedAdminTecnicoSegurancaRoute
  '/admin-tecnico/usuarios': typeof AuthenticatedAdminTecnicoUsuariosRoute
  '/admin-tecnico/vinculos': typeof AuthenticatedAdminTecnicoVinculosRoute
  '/admin/orgaos': typeof AuthenticatedAdminOrgaosRoute
  '/admin/solicitacoes': typeof AuthenticatedAdminSolicitacoesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ativar-convite': typeof AtivarConviteRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/alterar-orgao': typeof AuthenticatedAlterarOrgaoRoute
  '/area-de-trabalho': typeof AuthenticatedAreaDeTrabalhoRoute
  '/conta': typeof AuthenticatedContaRoute
  '/minha-equipe': typeof AuthenticatedMinhaEquipeRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/solicitar-acesso': typeof AuthenticatedSolicitarAcessoRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin-tecnico/acesso-emergencial': typeof AuthenticatedAdminTecnicoAcessoEmergencialRoute
  '/admin-tecnico/acesso-global': typeof AuthenticatedAdminTecnicoAcessoGlobalRoute
  '/admin-tecnico/administradores': typeof AuthenticatedAdminTecnicoAdministradoresRoute
  '/admin-tecnico/auditoria': typeof AuthenticatedAdminTecnicoAuditoriaRoute
  '/admin-tecnico/configuracoes': typeof AuthenticatedAdminTecnicoConfiguracoesRoute
  '/admin-tecnico/diagnosticos': typeof AuthenticatedAdminTecnicoDiagnosticosRoute
  '/admin-tecnico/orgaos': typeof AuthenticatedAdminTecnicoOrgaosRoute
  '/admin-tecnico/painel': typeof AuthenticatedAdminTecnicoPainelRoute
  '/admin-tecnico/seguranca': typeof AuthenticatedAdminTecnicoSegurancaRoute
  '/admin-tecnico/usuarios': typeof AuthenticatedAdminTecnicoUsuariosRoute
  '/admin-tecnico/vinculos': typeof AuthenticatedAdminTecnicoVinculosRoute
  '/admin/orgaos': typeof AuthenticatedAdminOrgaosRoute
  '/admin/solicitacoes': typeof AuthenticatedAdminSolicitacoesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/ativar-convite': typeof AtivarConviteRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/alterar-orgao': typeof AuthenticatedAlterarOrgaoRoute
  '/_authenticated/area-de-trabalho': typeof AuthenticatedAreaDeTrabalhoRoute
  '/_authenticated/conta': typeof AuthenticatedContaRoute
  '/_authenticated/minha-equipe': typeof AuthenticatedMinhaEquipeRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/_authenticated/solicitar-acesso': typeof AuthenticatedSolicitarAcessoRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/admin-tecnico/acesso-emergencial': typeof AuthenticatedAdminTecnicoAcessoEmergencialRoute
  '/_authenticated/admin-tecnico/acesso-global': typeof AuthenticatedAdminTecnicoAcessoGlobalRoute
  '/_authenticated/admin-tecnico/administradores': typeof AuthenticatedAdminTecnicoAdministradoresRoute
  '/_authenticated/admin-tecnico/auditoria': typeof AuthenticatedAdminTecnicoAuditoriaRoute
  '/_authenticated/admin-tecnico/configuracoes': typeof AuthenticatedAdminTecnicoConfiguracoesRoute
  '/_authenticated/admin-tecnico/diagnosticos': typeof AuthenticatedAdminTecnicoDiagnosticosRoute
  '/_authenticated/admin-tecnico/orgaos': typeof AuthenticatedAdminTecnicoOrgaosRoute
  '/_authenticated/admin-tecnico/painel': typeof AuthenticatedAdminTecnicoPainelRoute
  '/_authenticated/admin-tecnico/seguranca': typeof AuthenticatedAdminTecnicoSegurancaRoute
  '/_authenticated/admin-tecnico/usuarios': typeof AuthenticatedAdminTecnicoUsuariosRoute
  '/_authenticated/admin-tecnico/vinculos': typeof AuthenticatedAdminTecnicoVinculosRoute
  '/_authenticated/admin/orgaos': typeof AuthenticatedAdminOrgaosRoute
  '/_authenticated/admin/solicitacoes': typeof AuthenticatedAdminSolicitacoesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ativar-convite'
    | '/auth'
    | '/mcp'
    | '/redefinir-senha'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/alterar-orgao'
    | '/area-de-trabalho'
    | '/conta'
    | '/minha-equipe'
    | '/painel'
    | '/solicitar-acesso'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin-tecnico/acesso-emergencial'
    | '/admin-tecnico/acesso-global'
    | '/admin-tecnico/administradores'
    | '/admin-tecnico/auditoria'
    | '/admin-tecnico/configuracoes'
    | '/admin-tecnico/diagnosticos'
    | '/admin-tecnico/orgaos'
    | '/admin-tecnico/painel'
    | '/admin-tecnico/seguranca'
    | '/admin-tecnico/usuarios'
    | '/admin-tecnico/vinculos'
    | '/admin/orgaos'
    | '/admin/solicitacoes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ativar-convite'
    | '/auth'
    | '/mcp'
    | '/redefinir-senha'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/alterar-orgao'
    | '/area-de-trabalho'
    | '/conta'
    | '/minha-equipe'
    | '/painel'
    | '/solicitar-acesso'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin-tecnico/acesso-emergencial'
    | '/admin-tecnico/acesso-global'
    | '/admin-tecnico/administradores'
    | '/admin-tecnico/auditoria'
    | '/admin-tecnico/configuracoes'
    | '/admin-tecnico/diagnosticos'
    | '/admin-tecnico/orgaos'
    | '/admin-tecnico/painel'
    | '/admin-tecnico/seguranca'
    | '/admin-tecnico/usuarios'
    | '/admin-tecnico/vinculos'
    | '/admin/orgaos'
    | '/admin/solicitacoes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/ativar-convite'
    | '/auth'
    | '/mcp'
    | '/redefinir-senha'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/alterar-orgao'
    | '/_authenticated/area-de-trabalho'
    | '/_authenticated/conta'
    | '/_authenticated/minha-equipe'
    | '/_authenticated/painel'
    | '/_authenticated/solicitar-acesso'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/admin-tecnico/acesso-emergencial'
    | '/_authenticated/admin-tecnico/acesso-global'
    | '/_authenticated/admin-tecnico/administradores'
    | '/_authenticated/admin-tecnico/auditoria'
    | '/_authenticated/admin-tecnico/configuracoes'
    | '/_authenticated/admin-tecnico/diagnosticos'
    | '/_authenticated/admin-tecnico/orgaos'
    | '/_authenticated/admin-tecnico/painel'
    | '/_authenticated/admin-tecnico/seguranca'
    | '/_authenticated/admin-tecnico/usuarios'
    | '/_authenticated/admin-tecnico/vinculos'
    | '/_authenticated/admin/orgaos'
    | '/_authenticated/admin/solicitacoes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AtivarConviteRoute: typeof AtivarConviteRoute
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ativar-convite': {
      id: '/ativar-convite'
      path: '/ativar-convite'
      fullPath: '/ativar-convite'
      preLoaderRoute: typeof AtivarConviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/solicitar-acesso': {
      id: '/_authenticated/solicitar-acesso'
      path: '/solicitar-acesso'
      fullPath: '/solicitar-acesso'
      preLoaderRoute: typeof AuthenticatedSolicitarAcessoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/minha-equipe': {
      id: '/_authenticated/minha-equipe'
      path: '/minha-equipe'
      fullPath: '/minha-equipe'
      preLoaderRoute: typeof AuthenticatedMinhaEquipeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conta': {
      id: '/_authenticated/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof AuthenticatedContaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/area-de-trabalho': {
      id: '/_authenticated/area-de-trabalho'
      path: '/area-de-trabalho'
      fullPath: '/area-de-trabalho'
      preLoaderRoute: typeof AuthenticatedAreaDeTrabalhoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alterar-orgao': {
      id: '/_authenticated/alterar-orgao'
      path: '/alterar-orgao'
      fullPath: '/alterar-orgao'
      preLoaderRoute: typeof AuthenticatedAlterarOrgaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/solicitacoes': {
      id: '/_authenticated/admin/solicitacoes'
      path: '/admin/solicitacoes'
      fullPath: '/admin/solicitacoes'
      preLoaderRoute: typeof AuthenticatedAdminSolicitacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/orgaos': {
      id: '/_authenticated/admin/orgaos'
      path: '/admin/orgaos'
      fullPath: '/admin/orgaos'
      preLoaderRoute: typeof AuthenticatedAdminOrgaosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-tecnico/vinculos': {
      id: '/_authenticated/admin-tecnico/vinculos'
      path: '/admin-tecnico/vinculos'
      fullPath: '/admin-tecnico/vinculos'
      preLoaderRoute: typeof AuthenticatedAdminTecnicoVinculosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-tecnico/usuarios': {
      id: '/_authenticated/admin-tecnico/usuarios'
      path: '/admin-tecnico/usuarios'
      fullPath: '/admin-tecnico/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminTecnicoUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-tecnico/seguranca': {
      id: '/_authenticated/admin-tecnico/seguranca'
      path: '/admin-tecnico/seguranca'
      fullPath: '/admin-tecnico/seguranca'
      preLoaderRoute: typeof AuthenticatedAdminTecnicoSegurancaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-tecnico/painel': {
      id: '/_authenticated/admin-tecnico/painel'
      path: '/admin-tecnico/painel'
      fullPath: '/admin-tecnico/painel'
      preLoaderRoute: typeof AuthenticatedAdminTecnicoPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-tecnico/orgaos': {
      id: '/_authenticated/admin-tecnico/orgaos'
      path: '/admin-tecnico/orgaos'
      fullPath: '/admin-tecnico/orgaos'
      preLoaderRoute: typeof AuthenticatedAdminTecnicoOrgaosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-tecnico/diagnosticos': {
      id: '/_authenticated/admin-tecnico/diagnosticos'
      path: '/admin-tecnico/diagnosticos'
      fullPath: '/admin-tecnico/diagnosticos'
      preLoaderRoute: typeof AuthenticatedAdminTecnicoDiagnosticosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-tecnico/configuracoes': {
      id: '/_authenticated/admin-tecnico/configuracoes'
      path: '/admin-tecnico/configuracoes'
      fullPath: '/admin-tecnico/configuracoes'
      preLoaderRoute: typeof AuthenticatedAdminTecnicoConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-tecnico/auditoria': {
      id: '/_authenticated/admin-tecnico/auditoria'
      path: '/admin-tecnico/auditoria'
      fullPath: '/admin-tecnico/auditoria'
      preLoaderRoute: typeof AuthenticatedAdminTecnicoAuditoriaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-tecnico/administradores': {
      id: '/_authenticated/admin-tecnico/administradores'
      path: '/admin-tecnico/administradores'
      fullPath: '/admin-tecnico/administradores'
      preLoaderRoute: typeof AuthenticatedAdminTecnicoAdministradoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-tecnico/acesso-global': {
      id: '/_authenticated/admin-tecnico/acesso-global'
      path: '/admin-tecnico/acesso-global'
      fullPath: '/admin-tecnico/acesso-global'
      preLoaderRoute: typeof AuthenticatedAdminTecnicoAcessoGlobalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-tecnico/acesso-emergencial': {
      id: '/_authenticated/admin-tecnico/acesso-emergencial'
      path: '/admin-tecnico/acesso-emergencial'
      fullPath: '/admin-tecnico/acesso-emergencial'
      preLoaderRoute: typeof AuthenticatedAdminTecnicoAcessoEmergencialRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAlterarOrgaoRoute: typeof AuthenticatedAlterarOrgaoRoute
  AuthenticatedAreaDeTrabalhoRoute: typeof AuthenticatedAreaDeTrabalhoRoute
  AuthenticatedContaRoute: typeof AuthenticatedContaRoute
  AuthenticatedMinhaEquipeRoute: typeof AuthenticatedMinhaEquipeRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedSolicitarAcessoRoute: typeof AuthenticatedSolicitarAcessoRoute
  AuthenticatedAdminTecnicoAcessoEmergencialRoute: typeof AuthenticatedAdminTecnicoAcessoEmergencialRoute
  AuthenticatedAdminTecnicoAcessoGlobalRoute: typeof AuthenticatedAdminTecnicoAcessoGlobalRoute
  AuthenticatedAdminTecnicoAdministradoresRoute: typeof AuthenticatedAdminTecnicoAdministradoresRoute
  AuthenticatedAdminTecnicoAuditoriaRoute: typeof AuthenticatedAdminTecnicoAuditoriaRoute
  AuthenticatedAdminTecnicoConfiguracoesRoute: typeof AuthenticatedAdminTecnicoConfiguracoesRoute
  AuthenticatedAdminTecnicoDiagnosticosRoute: typeof AuthenticatedAdminTecnicoDiagnosticosRoute
  AuthenticatedAdminTecnicoOrgaosRoute: typeof AuthenticatedAdminTecnicoOrgaosRoute
  AuthenticatedAdminTecnicoPainelRoute: typeof AuthenticatedAdminTecnicoPainelRoute
  AuthenticatedAdminTecnicoSegurancaRoute: typeof AuthenticatedAdminTecnicoSegurancaRoute
  AuthenticatedAdminTecnicoUsuariosRoute: typeof AuthenticatedAdminTecnicoUsuariosRoute
  AuthenticatedAdminTecnicoVinculosRoute: typeof AuthenticatedAdminTecnicoVinculosRoute
  AuthenticatedAdminOrgaosRoute: typeof AuthenticatedAdminOrgaosRoute
  AuthenticatedAdminSolicitacoesRoute: typeof AuthenticatedAdminSolicitacoesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAlterarOrgaoRoute: AuthenticatedAlterarOrgaoRoute,
  AuthenticatedAreaDeTrabalhoRoute: AuthenticatedAreaDeTrabalhoRoute,
  AuthenticatedContaRoute: AuthenticatedContaRoute,
  AuthenticatedMinhaEquipeRoute: AuthenticatedMinhaEquipeRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedSolicitarAcessoRoute: AuthenticatedSolicitarAcessoRoute,
  AuthenticatedAdminTecnicoAcessoEmergencialRoute:
    AuthenticatedAdminTecnicoAcessoEmergencialRoute,
  AuthenticatedAdminTecnicoAcessoGlobalRoute:
    AuthenticatedAdminTecnicoAcessoGlobalRoute,
  AuthenticatedAdminTecnicoAdministradoresRoute:
    AuthenticatedAdminTecnicoAdministradoresRoute,
  AuthenticatedAdminTecnicoAuditoriaRoute:
    AuthenticatedAdminTecnicoAuditoriaRoute,
  AuthenticatedAdminTecnicoConfiguracoesRoute:
    AuthenticatedAdminTecnicoConfiguracoesRoute,
  AuthenticatedAdminTecnicoDiagnosticosRoute:
    AuthenticatedAdminTecnicoDiagnosticosRoute,
  AuthenticatedAdminTecnicoOrgaosRoute: AuthenticatedAdminTecnicoOrgaosRoute,
  AuthenticatedAdminTecnicoPainelRoute: AuthenticatedAdminTecnicoPainelRoute,
  AuthenticatedAdminTecnicoSegurancaRoute:
    AuthenticatedAdminTecnicoSegurancaRoute,
  AuthenticatedAdminTecnicoUsuariosRoute:
    AuthenticatedAdminTecnicoUsuariosRoute,
  AuthenticatedAdminTecnicoVinculosRoute:
    AuthenticatedAdminTecnicoVinculosRoute,
  AuthenticatedAdminOrgaosRoute: AuthenticatedAdminOrgaosRoute,
  AuthenticatedAdminSolicitacoesRoute: AuthenticatedAdminSolicitacoesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AtivarConviteRoute: AtivarConviteRoute,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
